influx:
  image: tutum/influxdb
  container_name: influx
  ports:
    - 8086:8086
    - 8083:8083
serializer:
  build: ../services/serializer/
  container_name: serializer
frontend:
  build: ../frontend/
  container_name: frontend
broker:
  build: ../services/broker/
  container_name: broker
sensor:
  build: ../services/sensor/
  container_name: sensor 
actuator:
  build: ../services/actuator/
  container_name: actuator
